### ISSUE TITLE
how to implement 1ms and 5ms periodic tasks cooperatively and 5ms task take 2ms?

### ISSUE THREAD

**Issue by anghd** [vishnumaiea/ptScheduler#4]

**Comment by vishnumaiea** [comment]
I assume you're asking for help rather than reporting an issue. Anyway, if you want to run two tasks, simply create a new ptScheduler object with 1 ms and 5 ms as given below.

```
ptScheduler taskOne = ptScheduler(1000); //1000 us = 1 ms
ptScheduler taskTwo = ptScheduler(5000); //5000 us = 1 ms
```

Just make sure that each of your tasks complete their operations under 2 ms. Otherwise timing won't be accurate. For example a microcontroller running at 16 MHz will take longer to execute a few operations compared to a microtontroller doing it at 100 MHz. Hope that helps.
